//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZachJohnson.Promptu.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionFormats {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionFormats() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZachJohnson.Promptu.Localization.ExceptionFormats", typeof(ExceptionFormats).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create an instance of the class &apos;{0}&apos; in the assembly &apos;{1}&apos;..
        /// </summary>
        internal static string CannotCreateInstanceOfClass {
            get {
                return ResourceManager.GetString("CannotCreateInstanceOfClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first character in the function&apos;s name can only be a letter or an underscore (&apos;_&apos;)..
        /// </summary>
        internal static string FunctionValidationFirstLetterInvalid {
            get {
                return ResourceManager.GetString("FunctionValidationFirstLetterInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; character at position {1} is invalid.  Characters between the first character and the last character can only be letters, digits, underscores (&apos;_&apos;), or periods..
        /// </summary>
        internal static string FunctionValidationLastLetterInvalid {
            get {
                return ResourceManager.GetString("FunctionValidationLastLetterInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last character is invalid.  The last character can only be a letter, digit, or underscore (&apos;_&apos;).
        /// </summary>
        internal static string FunctionValidationMiddleLetterInvalid {
            get {
                return ResourceManager.GetString("FunctionValidationMiddleLetterInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name &quot;{0}&quot; is unable to be used because it is reserved by Promptu.  Please choose another name..
        /// </summary>
        internal static string FunctionValidationNameIsReserved {
            get {
                return ResourceManager.GetString("FunctionValidationNameIsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  No assembly reference named &quot;{0}&quot; could be found..
        /// </summary>
        internal static string MissingAssemblyReference {
            get {
                return ResourceManager.GetString("MissingAssemblyReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The class &apos;{0}&apos; was not found in the assembly &apos;{1}&apos;..
        /// </summary>
        internal static string MissingClassInAssembly {
            get {
                return ResourceManager.GetString("MissingClassInAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method &apos;{0}&apos; with {3} string {4} was not found in the class &apos;{1}&apos; in the assembly &apos;{2}&apos;..
        /// </summary>
        internal static string MissingMethodInClass {
            get {
                return ResourceManager.GetString("MissingMethodInClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return value type mismatch while trying to invoke the method &apos;{0}&apos; in the class &apos;{1}&apos; in the assembly &apos;{2}&apos;.  
        ///
        ///Return value was of the type &apos;{3}&apos; but should have been of the type &apos;{4}&apos;..
        /// </summary>
        internal static string ReturnValueTypeMismatch {
            get {
                return ResourceManager.GetString("ReturnValueTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while trying to invoke the method &apos;{0}&apos; in the class &apos;{1}&apos; in the assembly &apos;{2}&apos;.  Message: {3}.
        /// </summary>
        internal static string UnableToInvokeMethod {
            get {
                return ResourceManager.GetString("UnableToInvokeMethod", resourceCulture);
            }
        }
    }
}
