//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZachJohnson.Promptu.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageFormats {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageFormats() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZachJohnson.Promptu.Localization.MessageFormats", typeof(MessageFormats).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operating system could not find &apos;{0}&apos;.  Make sure you typed the name correctly, and then try again..
        /// </summary>
        internal static string AllExceptCommandExecutionFailed {
            get {
                return ResourceManager.GetString("AllExceptCommandExecutionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot capture arguments, they will be undefined.
        /// </summary>
        internal static string ArgumentSubstitutionsCannotCaptureArguments {
            get {
                return ResourceManager.GetString("ArgumentSubstitutionsCannotCaptureArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while attempting to access &apos;{0}&apos;.  Error: {1}.
        /// </summary>
        internal static string AssemblyReferenceIOException {
            get {
                return ResourceManager.GetString("AssemblyReferenceIOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You renamed your assembly reference.  Would you like Promptu to update any references to &apos;{0}&apos;?.
        /// </summary>
        internal static string AssemblyReferenceNameChangeUpdateReferences {
            get {
                return ResourceManager.GetString("AssemblyReferenceNameChangeUpdateReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;.
        /// </summary>
        internal static string AssemblyReferenceNameDisplayFormat {
            get {
                return ResourceManager.GetString("AssemblyReferenceNameDisplayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred, so this feature is currently unavailable..
        /// </summary>
        internal static string CannotSetStartPromptuAutomatically {
            get {
                return ResourceManager.GetString("CannotSetStartPromptuAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use parameters greater than or equal to &apos;{0}&apos;, they will be undefined.
        /// </summary>
        internal static string CannotUseParametersGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("CannotUseParametersGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; could not be found.  Do you want to edit &apos;{1}&apos;?.
        /// </summary>
        internal static string CommandExecutionFailed {
            get {
                return ResourceManager.GetString("CommandExecutionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; could not be opened because it is locked by another program.  Do you want to edit &apos;{1}&apos;?.
        /// </summary>
        internal static string CommandExecutionFailedLocked {
            get {
                return ResourceManager.GetString("CommandExecutionFailedLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; could not be opened because it is locked by another program..
        /// </summary>
        internal static string CommandExecutionFailedLockedNoEdit {
            get {
                return ResourceManager.GetString("CommandExecutionFailedLockedNoEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; could not be found..
        /// </summary>
        internal static string CommandExecutionFailedNoEdit {
            get {
                return ResourceManager.GetString("CommandExecutionFailedNoEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An problem occurred while attempting to open &apos;{0}&apos;.  Do you want to edit &apos;{1}&apos;?.
        /// </summary>
        internal static string CommandExecutionFailedWin32 {
            get {
                return ResourceManager.GetString("CommandExecutionFailedWin32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An problem occurred while attempting to open &apos;{0}&apos;..
        /// </summary>
        internal static string CommandExecutionFailedWin32NoEdit {
            get {
                return ResourceManager.GetString("CommandExecutionFailedWin32NoEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is not allowed at the end of your command&apos;s name..
        /// </summary>
        internal static string CommandNameCharacterCannotBeAtEnd {
            get {
                return ResourceManager.GetString("CommandNameCharacterCannotBeAtEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is not allowed at the beginning of your command&apos;s name..
        /// </summary>
        internal static string CommandNameCharacterCannotBeAtStart {
            get {
                return ResourceManager.GetString("CommandNameCharacterCannotBeAtStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;.
        /// </summary>
        internal static string CommandNameDisplayFormat {
            get {
                return ResourceManager.GetString("CommandNameDisplayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is not allowed in command names..
        /// </summary>
        internal static string CommandNameInvalidChar {
            get {
                return ResourceManager.GetString("CommandNameInvalidChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;.&quot; is not allowed at the end of an alias for your command..
        /// </summary>
        internal static string CommandNameInvalidDotAtEndAlias {
            get {
                return ResourceManager.GetString("CommandNameInvalidDotAtEndAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;.&quot; is not allowed at the end of your command&apos;s name..
        /// </summary>
        internal static string CommandNameInvalidDotAtEndName {
            get {
                return ResourceManager.GetString("CommandNameInvalidDotAtEndName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;.&quot; is not allowed at the beginning of an alias for your command..
        /// </summary>
        internal static string CommandNameInvalidDotAtStartAlias {
            get {
                return ResourceManager.GetString("CommandNameInvalidDotAtStartAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;.&quot; is not allowed at the beginning of your command&apos;s name..
        /// </summary>
        internal static string CommandNameInvalidDotAtStartName {
            get {
                return ResourceManager.GetString("CommandNameInvalidDotAtStartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spaces are not allowed in your command&apos;s name..
        /// </summary>
        internal static string CommandNameNoSpaces {
            get {
                return ResourceManager.GetString("CommandNameNoSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is already published at &apos;{1}&apos;.  Are you sure you want to change the publish location of &apos;{0}&apos;?  (Only one publish location may be specified at a time.).
        /// </summary>
        internal static string ConfirmChangePublishLocation {
            get {
                return ResourceManager.GetString("ConfirmChangePublishLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the assembly reference &apos;{0}&apos;?.
        /// </summary>
        internal static string ConfirmDeleteAssemblyReference {
            get {
                return ResourceManager.GetString("ConfirmDeleteAssemblyReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the following assembly references?.
        /// </summary>
        internal static string ConfirmDeleteAssemblyReferences {
            get {
                return ResourceManager.GetString("ConfirmDeleteAssemblyReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete &apos;{0}&apos;?.
        /// </summary>
        internal static string ConfirmDeleteCommand {
            get {
                return ResourceManager.GetString("ConfirmDeleteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the following commands?.
        /// </summary>
        internal static string ConfirmDeleteCommands {
            get {
                return ResourceManager.GetString("ConfirmDeleteCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the function &apos;{0}&apos;?.
        /// </summary>
        internal static string ConfirmDeleteFunction {
            get {
                return ResourceManager.GetString("ConfirmDeleteFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the following functions?.
        /// </summary>
        internal static string ConfirmDeleteFunctions {
            get {
                return ResourceManager.GetString("ConfirmDeleteFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete &apos;{0}&apos;?.
        /// </summary>
        internal static string ConfirmDeleteList {
            get {
                return ResourceManager.GetString("ConfirmDeleteList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete &apos;{0}&apos;?  (Operation cannot be undone).
        /// </summary>
        internal static string ConfirmDeleteProfile {
            get {
                return ResourceManager.GetString("ConfirmDeleteProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the value list &apos;{0}&apos;?.
        /// </summary>
        internal static string ConfirmDeleteValueList {
            get {
                return ResourceManager.GetString("ConfirmDeleteValueList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the following value lists?.
        /// </summary>
        internal static string ConfirmDeleteValueLists {
            get {
                return ResourceManager.GetString("ConfirmDeleteValueLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;
        ///Do you want to edit &apos;{1}&apos;?.
        /// </summary>
        internal static string ConversionExceptionOnExecuteCommand {
            get {
                return ResourceManager.GetString("ConversionExceptionOnExecuteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is corrupted.  Data may be lost.
        ///Message:
        ///{1}.
        /// </summary>
        internal static string CorruptedFile {
            get {
                return ResourceManager.GetString("CorruptedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; uses &apos;@MULTI@&apos; but does not actually execute any commands.  Do you want to edit &apos;{0}&apos;?.
        /// </summary>
        internal static string EmptyMultiCommand {
            get {
                return ResourceManager.GetString("EmptyMultiCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; uses &apos;@MULTI@&apos; but does not actually execute any commands..
        /// </summary>
        internal static string EmptyMultiCommandNoEdit {
            get {
                return ResourceManager.GetString("EmptyMultiCommandNoEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///Do you want to edit &apos;{1}&apos;?.
        /// </summary>
        internal static string ErrorOnFunctionInvoke {
            get {
                return ResourceManager.GetString("ErrorOnFunctionInvoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following errors occured while attempting to compile &apos;{0}&apos;:
        ///{1}.
        /// </summary>
        internal static string ExecuteFunctionCompileError {
            get {
                return ResourceManager.GetString("ExecuteFunctionCompileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promptu cannot list the contents of &quot;{0}&quot; because access is denied.
        ///
        ///This might be fixed by running Promptu with elevated privileges..
        /// </summary>
        internal static string FileSystemSuggestionUnauthorizedAccess {
            get {
                return ResourceManager.GetString("FileSystemSuggestionUnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promptu cannot list the contents of &quot;{0}&quot; because access is denied..
        /// </summary>
        internal static string FileSystemSuggestionUnauthorizedAccessRunningElevated {
            get {
                return ResourceManager.GetString("FileSystemSuggestionUnauthorizedAccessRunningElevated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is not allowed in your function&apos;s name.
        ///Function names can only contain letters, digits, underscores (&quot;_&quot;), and periods (&quot;.&quot;)..
        /// </summary>
        internal static string FunctionEditorAlwaysInvalidChar {
            get {
                return ResourceManager.GetString("FunctionEditorAlwaysInvalidChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is not allowed at the beginning of your function&apos;s name.
        ///The first character in your function&apos;s name can be a letter or an underscore (&quot;_&quot;)..
        /// </summary>
        internal static string FunctionEditorInvalidFirstChar {
            get {
                return ResourceManager.GetString("FunctionEditorInvalidFirstChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;.
        /// </summary>
        internal static string FunctionNameDisplayFormat {
            get {
                return ResourceManager.GetString("FunctionNameDisplayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;.&quot; is not allowed at the end of your function&apos;s name..
        /// </summary>
        internal static string FunctionNameInvalidDotAtEnd {
            get {
                return ResourceManager.GetString("FunctionNameInvalidDotAtEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        internal static string GeneralError {
            get {
                return ResourceManager.GetString("GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hotkey &apos;{0}&apos; is already in use.  Please choose another hotkey or check &quot;Override if already used&quot;..
        /// </summary>
        internal static string HotkeyUnavailable {
            get {
                return ResourceManager.GetString("HotkeyUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hotkey &apos;{0}&apos; is already in use.
        ///Please choose another hotkey..
        /// </summary>
        internal static string HotkeyUnavailableForDialog {
            get {
                return ResourceManager.GetString("HotkeyUnavailableForDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is either corrupt or is not a Promptu package/shared list..
        /// </summary>
        internal static string InternalPackageError {
            get {
                return ResourceManager.GetString("InternalPackageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; does not take &apos;{1}&apos; arguments.
        /// </summary>
        internal static string InvalidParameterCountPlural {
            get {
                return ResourceManager.GetString("InvalidParameterCountPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;does not take &apos;{1}&apos; argument.
        /// </summary>
        internal static string InvalidParameterCountSingular {
            get {
                return ResourceManager.GetString("InvalidParameterCountSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while attempting to delete &apos;{0}&apos;.
        /// </summary>
        internal static string IOExceptionOnDeleteList {
            get {
                return ResourceManager.GetString("IOExceptionOnDeleteList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are errors which must be fixed before you can test the command (see Error List)..
        /// </summary>
        internal static string ItlMustBeFixedBeforeTest {
            get {
                return ResourceManager.GetString("ItlMustBeFixedBeforeTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        internal static string ItlParseErrorMessageFormat {
            get {
                return ResourceManager.GetString("ItlParseErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while parsing the arguments (&apos;{1}&apos;) for &apos;{0}&apos;:.
        /// </summary>
        internal static string ItlParseErrorOnArguments {
            get {
                return ResourceManager.GetString("ItlParseErrorOnArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Do you want to edit &apos;{1}&apos;?.
        /// </summary>
        internal static string ItlParseErrorOnCommandExecute {
            get {
                return ResourceManager.GetString("ItlParseErrorOnCommandExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while parsing the execution path (&apos;{1}&apos;) for &apos;{0}&apos;:.
        /// </summary>
        internal static string ItlParseErrorOnExecutionPath {
            get {
                return ResourceManager.GetString("ItlParseErrorOnExecutionPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while parsing the startup directory (&apos;{1}&apos;) for &apos;{0}&apos;:.
        /// </summary>
        internal static string ItlParseErrorOnStartupDirectory {
            get {
                return ResourceManager.GetString("ItlParseErrorOnStartupDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing &quot;String[]&quot; or &quot;ValueList&quot; function &apos;{0}&apos;.
        /// </summary>
        internal static string MissingStringArrayOrValueListFunction {
            get {
                return ResourceManager.GetString("MissingStringArrayOrValueListFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing &quot;String&quot; function &apos;{0}&apos;.
        /// </summary>
        internal static string MissingStringFunction {
            get {
                return ResourceManager.GetString("MissingStringFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command &apos;{0}&apos;, referenced by the &apos;@MULTI@&apos; command &apos;{1}&apos;, does not take {2}.  Do you want to edit &apos;{1}&apos;?.
        /// </summary>
        internal static string MultiCalledCommandInvalidParameterCount {
            get {
                return ResourceManager.GetString("MultiCalledCommandInvalidParameterCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command &apos;{0}&apos;, referenced by the &apos;@MULTI@&apos; command &apos;{1}&apos;, does not take {2}..
        /// </summary>
        internal static string MultiCalledCommandInvalidParameterCountNoEdit {
            get {
                return ResourceManager.GetString("MultiCalledCommandInvalidParameterCountNoEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing command &apos;{0}&apos; for &apos;@MULTI@&apos; command &apos;{1}&apos;.  Do you want to edit &apos;{1}&apos;?.
        /// </summary>
        internal static string MultiCommandMissingCommand {
            get {
                return ResourceManager.GetString("MultiCommandMissingCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing command &apos;{0}&apos; for &apos;@MULTI@&apos; command &apos;{1}&apos;..
        /// </summary>
        internal static string MultiCommandMissingCommandNoEdit {
            get {
                return ResourceManager.GetString("MultiCommandMissingCommandNoEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name &apos;{0}&apos; cannot be used because it is reserved by a built-in command..
        /// </summary>
        internal static string NameIsReserved {
            get {
                return ResourceManager.GetString("NameIsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promptu cannot read the file &apos;{0}&apos; because it was made with an incompatible later version of Promptu.  Please update your installation of Promptu to enable reading this file..
        /// </summary>
        internal static string NewerPackageUnreadableMessageFormat {
            get {
                return ResourceManager.GetString("NewerPackageUnreadableMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The assembly &apos;{0}&apos; was not in the package.  Any functions relying on it will not work..
        /// </summary>
        internal static string PackageIsMissingAssembly {
            get {
                return ResourceManager.GetString("PackageIsMissingAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} parameters.
        /// </summary>
        internal static string ParameterFormatPlural {
            get {
                return ResourceManager.GetString("ParameterFormatPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} parameter.
        /// </summary>
        internal static string ParameterFormatSingular {
            get {
                return ResourceManager.GetString("ParameterFormatSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: &apos;{0}&apos; could not be found..
        /// </summary>
        internal static string PathNotFoundError {
            get {
                return ResourceManager.GetString("PathNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The profile is corrupted and cannot be loaded.  Please choose another profile..
        /// </summary>
        internal static string ProfileIsCorrupted {
            get {
                return ResourceManager.GetString("ProfileIsCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;
        ///Do you want to edit &apos;{1}&apos;?.
        /// </summary>
        internal static string SelfReferenceOnExecuteCommand {
            get {
                return ResourceManager.GetString("SelfReferenceOnExecuteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Cannot resolve the path specified in &apos;{0}&apos;; it ends up referencing itself again..
        /// </summary>
        internal static string SelfReferencingRecursiveDirectoryResolvingReference {
            get {
                return ResourceManager.GetString("SelfReferencingRecursiveDirectoryResolvingReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: &apos;{0}&apos;, which is a multi command, ends up calling itself again..
        /// </summary>
        internal static string SelfReferencingRecursiveMultiCall {
            get {
                return ResourceManager.GetString("SelfReferencingRecursiveMultiCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully imported {0} SlickRun MagicWord{1}..
        /// </summary>
        internal static string SlickRunImportMessage {
            get {
                return ResourceManager.GetString("SlickRunImportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} &apos;String&apos; parameters.
        /// </summary>
        internal static string StringParameterFormatPlural {
            get {
                return ResourceManager.GetString("StringParameterFormatPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} &apos;String&apos; parameter.
        /// </summary>
        internal static string StringParameterFormatSingular {
            get {
                return ResourceManager.GetString("StringParameterFormatSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough parameters were supplied.  Do you want to edit &apos;{0}&apos;?.
        /// </summary>
        internal static string TooLittleNumberOfParametersForFunction {
            get {
                return ResourceManager.GetString("TooLittleNumberOfParametersForFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough parameters were supplied..
        /// </summary>
        internal static string TooLittleNumberOfParametersForFunctionNoEdit {
            get {
                return ResourceManager.GetString("TooLittleNumberOfParametersForFunctionNoEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many parameters were supplied.  Do you want to edit &apos;{0}&apos;?.
        /// </summary>
        internal static string TooManyParametersForFunction {
            get {
                return ResourceManager.GetString("TooManyParametersForFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many parameters were supplied..
        /// </summary>
        internal static string TooManyParametersForFunctionNoEdit {
            get {
                return ResourceManager.GetString("TooManyParametersForFunctionNoEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to populate the suggestion provider because the following errors 
        ///occured while attempting to compile the function invocation:
        ///
        ///{0}.
        /// </summary>
        internal static string UnableToPopulateSuggestionProviderCompileError {
            get {
                return ResourceManager.GetString("UnableToPopulateSuggestionProviderCompileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to populate the suggestion provider because the following errors 
        ///occured while attempting to compile the filter:
        ///
        ///{0}.
        /// </summary>
        internal static string UnableToPopulateSuggestionProviderFilterCompileError {
            get {
                return ResourceManager.GetString("UnableToPopulateSuggestionProviderFilterCompileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to populate the suggestion provider because the following errors 
        ///occured while attempting to evaluate the expression:
        ///
        ///{0}.
        /// </summary>
        internal static string UnableToPopulateSuggestionProviderInvocationError {
            get {
                return ResourceManager.GetString("UnableToPopulateSuggestionProviderInvocationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///
        ///Please verify that you have write permissions and then try again..
        /// </summary>
        internal static string UnauthorizedAccessExceptionGeneral {
            get {
                return ResourceManager.GetString("UnauthorizedAccessExceptionGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///
        ///Promptu will have to close.
        ///Please verify that you have write permissions and then restart Promptu..
        /// </summary>
        internal static string UnauthorizedAccessExceptionGlobalCatch {
            get {
                return ResourceManager.GetString("UnauthorizedAccessExceptionGlobalCatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you also like to delete the published file &apos;{0}&apos;?.
        /// </summary>
        internal static string UnpublishAlsoDeleteFile {
            get {
                return ResourceManager.GetString("UnpublishAlsoDeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: &apos;Name&apos; must be more than spaces..
        /// </summary>
        internal static string ValueListNameCannotBeEmptyWhitespace {
            get {
                return ResourceManager.GetString("ValueListNameCannotBeEmptyWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;.
        /// </summary>
        internal static string ValueListNameDisplayFormat {
            get {
                return ResourceManager.GetString("ValueListNameDisplayFormat", resourceCulture);
            }
        }
    }
}
