//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZachJohnson.Promptu.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ItlMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ItlMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZachJohnson.Promptu.Localization.ItlMessages", typeof(ItlMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument number cannot be zero.
        /// </summary>
        internal static string ArgumentNumberCannotBeZero {
            get {
                return ResourceManager.GetString("ArgumentNumberCannotBeZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument number expected.
        /// </summary>
        internal static string ArgumentNumberExpected {
            get {
                return ResourceManager.GetString("ArgumentNumberExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument number or &apos;n&apos; expected.
        /// </summary>
        internal static string ArgumentNumberOrNExpected {
            get {
                return ResourceManager.GetString("ArgumentNumberOrNExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;(&apos; and &apos;)&apos; expected.
        /// </summary>
        internal static string BothParenthesesExpected {
            get {
                return ResourceManager.GetString("BothParenthesesExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character expected.
        /// </summary>
        internal static string CharacterExpected {
            get {
                return ResourceManager.GetString("CharacterExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;&gt;&apos; expected.
        /// </summary>
        internal static string CloseAngleBracketExpected {
            get {
                return ResourceManager.GetString("CloseAngleBracketExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;)&apos; expected.
        /// </summary>
        internal static string CloseParenthesesExpected {
            get {
                return ResourceManager.GetString("CloseParenthesesExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos; &quot; &apos; expected.
        /// </summary>
        internal static string EndQuoteExpected {
            get {
                return ResourceManager.GetString("EndQuoteExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression expected.
        /// </summary>
        internal static string ExpressionExpected {
            get {
                return ResourceManager.GetString("ExpressionExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First argument number &gt; last argument number.
        /// </summary>
        internal static string FirstArgumentNumberLessThanLastArgumentNumber {
            get {
                return ResourceManager.GetString("FirstArgumentNumberLessThanLastArgumentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; expected.
        /// </summary>
        internal static string GeneralExpectedFormat {
            get {
                return ResourceManager.GetString("GeneralExpectedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; not expected.
        /// </summary>
        internal static string GeneralNotExpectedFormat {
            get {
                return ResourceManager.GetString("GeneralNotExpectedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;-&apos; expected.
        /// </summary>
        internal static string HypenExpected {
            get {
                return ResourceManager.GetString("HypenExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is too big for a 32 bit integer.
        /// </summary>
        internal static string Int32Overflow {
            get {
                return ResourceManager.GetString("Int32Overflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; not understood.
        /// </summary>
        internal static string NotUnderstoodFormat {
            get {
                return ResourceManager.GetString("NotUnderstoodFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;(&apos; expected.
        /// </summary>
        internal static string OpenParenthesesExpected {
            get {
                return ResourceManager.GetString("OpenParenthesesExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter missing.
        /// </summary>
        internal static string ParameterMissing {
            get {
                return ResourceManager.GetString("ParameterMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;?&apos; expected.
        /// </summary>
        internal static string QuestionMarkExpected {
            get {
                return ResourceManager.GetString("QuestionMarkExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String literal not expected.
        /// </summary>
        internal static string StringLiteralNotExpected {
            get {
                return ResourceManager.GetString("StringLiteralNotExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized escape sequence.
        /// </summary>
        internal static string UnrecognizedEscapeSequence {
            get {
                return ResourceManager.GetString("UnrecognizedEscapeSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value before the hyphen cannot be &apos;n&apos;.
        /// </summary>
        internal static string ValueBeforeHypenCannotBeN {
            get {
                return ResourceManager.GetString("ValueBeforeHypenCannotBeN", resourceCulture);
            }
        }
    }
}
