//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZachJohnson.Promptu.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Promptu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Promptu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZachJohnson.Promptu.Localization.Promptu", typeof(Promptu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha.
        /// </summary>
        internal static string Alpha {
            get {
                return ResourceManager.GetString("Alpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promptu is already started..
        /// </summary>
        internal static string AppAlreadyStartedMessage {
            get {
                return ResourceManager.GetString("AppAlreadyStartedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promptu.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promptu is up to date..
        /// </summary>
        internal static string AppUpToDate {
            get {
                return ResourceManager.GetString("AppUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: An assembly reference with that name already exists in the selected list.  Please choose another name..
        /// </summary>
        internal static string AssemblyReferenceAlreadyExistsMessage {
            get {
                return ResourceManager.GetString("AssemblyReferenceAlreadyExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid hotkey key..
        /// </summary>
        internal static string BadHotkeyMessage {
            get {
                return ResourceManager.GetString("BadHotkeyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beta.
        /// </summary>
        internal static string Beta {
            get {
                return ResourceManager.GetString("Beta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is only one profile.  You cannot delete it until you have added another one to take its place..
        /// </summary>
        internal static string CannotDeleteProfileBecauseThereIsOnlyOne {
            get {
                return ResourceManager.GetString("CannotDeleteProfileBecauseThereIsOnlyOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A skin featuring a prompt similar to the one from versions prior to Promptu 0.9.
        /// </summary>
        internal static string ClassicSkinDescription {
            get {
                return ResourceManager.GetString("ClassicSkinDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic.
        /// </summary>
        internal static string ClassicSkinName {
            get {
                return ResourceManager.GetString("ClassicSkinName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: The name &apos;{0}&apos; is already in use..
        /// </summary>
        internal static string CommandNameAlreadyExists {
            get {
                return ResourceManager.GetString("CommandNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: The following names are already in use:
        ///{0}.
        /// </summary>
        internal static string CommandNamesAlreadyExist {
            get {
                return ResourceManager.GetString("CommandNamesAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to hibernate your computer?.
        /// </summary>
        internal static string ConfirmHibernate {
            get {
                return ResourceManager.GetString("ConfirmHibernate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to log off your computer?.
        /// </summary>
        internal static string ConfirmLogoff {
            get {
                return ResourceManager.GetString("ConfirmLogoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reboot your computer?.
        /// </summary>
        internal static string ConfirmReboot {
            get {
                return ResourceManager.GetString("ConfirmReboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to shut down your computer?.
        /// </summary>
        internal static string ConfirmShutdown {
            get {
                return ResourceManager.GetString("ConfirmShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ©{0} Zach Johnson.  All rights reserved..
        /// </summary>
        internal static string CopyrightFormat {
            get {
                return ResourceManager.GetString("CopyrightFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while attempting to take you to the .NET 4 download page.  Please manually visit &quot;www.promptulauncher.com/get-dotnet&quot;..
        /// </summary>
        internal static string CouldNotVisitDotNet4Download {
            get {
                return ResourceManager.GetString("CouldNotVisitDotNet4Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Plugins&gt;
        ///  &lt;Plugin id=&quot;http://promptulauncher.com/plugins/calculator&quot;&gt;
        ///  &lt;/Plugin&gt;
        ///  &lt;Plugin id=&quot;http://promptulauncher.com/plugins/notes&quot;&gt;
        ///  &lt;/Plugin&gt;
        ///&lt;/Plugins&gt;.
        /// </summary>
        internal static string DefaultPluginXml {
            get {
                return ResourceManager.GetString("DefaultPluginXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default skin used by Promptu..
        /// </summary>
        internal static string DefaultSkinDescription {
            get {
                return ResourceManager.GetString("DefaultSkinDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string DefaultSkinName {
            get {
                return ResourceManager.GetString("DefaultSkinName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while attempting to visit the help section of the Promptu website.
        ///You can manually visit the help section at: http://www.promptulauncher.com/docs/.
        /// </summary>
        internal static string ErrorVisitingHelpOnWebsite {
            get {
                return ResourceManager.GetString("ErrorVisitingHelpOnWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while attempting to visit the website..
        /// </summary>
        internal static string ErrorVisitingWebsite {
            get {
                return ResourceManager.GetString("ErrorVisitingWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: &quot;{0}&quot;{1}.
        /// </summary>
        internal static string FeedbackMessageErrorToStringFormat {
            get {
                return ResourceManager.GetString("FeedbackMessageErrorToStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  at position {0}.
        /// </summary>
        internal static string FeedbackMessageLocationFormat {
            get {
                return ResourceManager.GetString("FeedbackMessageLocationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message: &quot;{0}&quot;{1}.
        /// </summary>
        internal static string FeedbackMessageMessageToStringFormat {
            get {
                return ResourceManager.GetString("FeedbackMessageMessageToStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: &quot;{0}&quot;{1}.
        /// </summary>
        internal static string FeedbackMessageWarningToStringFormat {
            get {
                return ResourceManager.GetString("FeedbackMessageWarningToStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: A function with that name and number of parameters already exists..
        /// </summary>
        internal static string FunctionAlreadyExistsMessage {
            get {
                return ResourceManager.GetString("FunctionAlreadyExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} with {1} parameters.
        /// </summary>
        internal static string FunctionIdentifierFormatPlural {
            get {
                return ResourceManager.GetString("FunctionIdentifierFormatPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} with {1} parameter.
        /// </summary>
        internal static string FunctionIdentifierFormatSingular {
            get {
                return ResourceManager.GetString("FunctionIdentifierFormatSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Meta&gt;
        ///  &lt;Data revision=&quot;1&quot;/&gt;
        ///&lt;/Meta&gt;.
        /// </summary>
        internal static string ListMeta {
            get {
                return ResourceManager.GetString("ListMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details on the error have been logged.  Please contact Promptu Support at support@promptulauncher.com to help us fix this problem.
        ///
        ///Thank you,
        ///The Promptu team.
        /// </summary>
        internal static string ManagedUnhandledException {
            get {
                return ResourceManager.GetString("ManagedUnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred and Promptu will have to close.
        /// </summary>
        internal static string ManagedUnhandledMainInstructions {
            get {
                return ResourceManager.GetString("ManagedUnhandledMainInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NewCommandName {
            get {
                return ResourceManager.GetString("NewCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New List{+}.
        /// </summary>
        internal static string NewListNameBasicFomat {
            get {
                return ResourceManager.GetString("NewListNameBasicFomat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - ({number}).
        /// </summary>
        internal static string NewListNameInsertFormat {
            get {
                return ResourceManager.GetString("NewListNameInsertFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Choosing Windows+R as your hotkey will override the built-in Windows Run dialog.  If this is not what you want to do, please select another hotkey..
        /// </summary>
        internal static string OverridingWinRWarning {
            get {
                return ResourceManager.GetString("OverridingWinRWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parameters.
        /// </summary>
        internal static string ParameterPlural {
            get {
                return ResourceManager.GetString("ParameterPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parameter.
        /// </summary>
        internal static string ParameterSingular {
            get {
                return ResourceManager.GetString("ParameterSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin updates successful.  Promptu will now restart..
        /// </summary>
        internal static string PluginUpdateSuccessful {
            get {
                return ResourceManager.GetString("PluginUpdateSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promptu needs the .NET Framework 4 to run.  Would you like to go to the Microsoft download page to get it?.
        /// </summary>
        internal static string PromptuNeedsDotNet4 {
            get {
                return ResourceManager.GetString("PromptuNeedsDotNet4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;.
        /// </summary>
        internal static string ReservedNameFormat {
            get {
                return ResourceManager.GetString("ReservedNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , .
        /// </summary>
        internal static string ReservedNamesCommaFormat {
            get {
                return ResourceManager.GetString("ReservedNamesCommaFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , and .
        /// </summary>
        internal static string ReservedNamesCommandAndFormat {
            get {
                return ResourceManager.GetString("ReservedNamesCommandAndFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like Promptu to automatically start when your computer starts?.
        /// </summary>
        internal static string StartWithComputer {
            get {
                return ResourceManager.GetString("StartWithComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like it works....
        /// </summary>
        internal static string TestCommandSuceededMessageDefault {
            get {
                return ResourceManager.GetString("TestCommandSuceededMessageDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like it works ;-).
        /// </summary>
        internal static string TestCommandSuceededMessageForSlickRunUsers {
            get {
                return ResourceManager.GetString("TestCommandSuceededMessageForSlickRunUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promptu was unable to create a profile using the on-disc template.  Would you like to reset the on-disc template and try again? (recommended)  If not, Promptu will have to close..
        /// </summary>
        internal static string UnableToCreateNewProfile {
            get {
                return ResourceManager.GetString("UnableToCreateNewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promptu was unable to create a profile using the on-disc template.  Would you like to reset the on-disc template and try again? (recommended).
        /// </summary>
        internal static string UnableToCreateNewProfileSetupDialog {
            get {
                return ResourceManager.GetString("UnableToCreateNewProfileSetupDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hotkey key could not be loaded. Defaulted back to &apos;Q&apos;..
        /// </summary>
        internal static string UnableToLoadHotkeyMessage {
            get {
                return ResourceManager.GetString("UnableToLoadHotkeyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Notes hotkey key could not be loaded. Defaulted back to &apos;J&apos;..
        /// </summary>
        internal static string UnableToLoadNotesHotkeyMessage {
            get {
                return ResourceManager.GetString("UnableToLoadNotesHotkeyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string UnknownLocker {
            get {
                return ResourceManager.GetString("UnknownLocker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details on the error cannot be logged.  Please contact Promptu Support at support@promptulauncher.com so we can try to fix this problem.
        ///
        ///Thank you,
        ///The Promptu team.
        /// </summary>
        internal static string UnmanagedUnhandledException {
            get {
                return ResourceManager.GetString("UnmanagedUnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred and Promptu will have to close.
        /// </summary>
        internal static string UnmanagedUnhandledMainInstructions {
            get {
                return ResourceManager.GetString("UnmanagedUnhandledMainInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update to Promptu is available.
        ///Would you like Promptu to download and install it for you?.
        /// </summary>
        internal static string UpdateAvailableAskIfDownload {
            get {
                return ResourceManager.GetString("UpdateAvailableAskIfDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while attempting to download the update..
        /// </summary>
        internal static string UpdateDownloadError {
            get {
                return ResourceManager.GetString("UpdateDownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded {0} kB.
        /// </summary>
        internal static string UpdateDownloadProgressFormat {
            get {
                return ResourceManager.GetString("UpdateDownloadProgressFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded {0} of [1] kB.
        /// </summary>
        internal static string UpdateDownloadProgressFormatWithTotalLength {
            get {
                return ResourceManager.GetString("UpdateDownloadProgressFormatWithTotalLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while attempting to update Promptu..
        /// </summary>
        internal static string UpdateError {
            get {
                return ResourceManager.GetString("UpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promptu could not successfully contact the web server to determine if there is an update. 
        ///
        ///Are you behind a proxy server?  Proxy settings can be configured in the Updates section under the Options tab in the Setup dialog.
        ///
        ///If this problem persists, you can manually download the latest version of Promptu at http://www.PromptuLauncher.com/ and install it over your current installation.  Your profile(s) (commands, etc) will not be overwritten..
        /// </summary>
        internal static string UpdateErrorContactingWebServer {
            get {
                return ResourceManager.GetString("UpdateErrorContactingWebServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update successful.  Promptu will now restart..
        /// </summary>
        internal static string UpdateSuccessful {
            get {
                return ResourceManager.GetString("UpdateSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: A value list with that name already exists..
        /// </summary>
        internal static string ValueListAlreadyExistsMessage {
            get {
                return ResourceManager.GetString("ValueListAlreadyExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.{1}.{2}.{3}.
        /// </summary>
        internal static string VersionFormat {
            get {
                return ResourceManager.GetString("VersionFormat", resourceCulture);
            }
        }
    }
}
